# Generated by Django 4.1.13 on 2024-02-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='No snippet', help_text='The snippet of the post.', max_length=250),
        ),
    ]
