# Generated by Django 4.1.13 on 2024-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='The slug of the post.', max_length=200, unique_for_date='publish'),
        ),
    ]
